### ISSUE TITLE
[feature] remain open after clicking a link (floating window / browser view)

### ISSUE THREAD

**Issue by codybrom** [tvler/streetpass#10]
I use Streetpass in Arc and so clicking a link requires me to go through several steps to get back to the streetpass window. Would instead like to see it optionally stay open as a floating window.

**Comment by tvler** [comment]
Interesting idea! Maybe by holding the command button? (Same key that you would hold to open in a background tab for a normal link)

**Comment by codybrom** [comment]
Just gave that a try and it didn't work for Chrome or Arc. Alternatively, if I could open the page in my main browser window that could be interesting.

I tried visiting chrome-extension://_xxxxxxxxlongidherexxxxxx_/src/popup.html and that gave me a pretty good experience, but it closed the tab after I click a link. Would love to meet somewhere in the middle! I just want to look open a bunch of tabs and look at the people I've collected. 😄

**Comment by tvler** [comment]
This has been fixed in the next update 2023.8! Currently in review on the chrome webstore https://github.com/tvler/streetpass/blob/main/extension/src/popup.tsx#L24

Now you can hold the command button while clicking a link on the popup, and the url will open in a background tab leaving the popup open
