### ISSUE TITLE
Find people from their Twitter profile

### ISSUE THREAD

**Issue by jerodsanto** [tvler/streetpass#12]
It'd be cool to add special handling for twitter.com URLs so that if the current user profile has their mastodon handle in their name, handle, or bio somewhere then StreetPass would extract it and provide an easy click to follow experience.

_(We could do GitHub profiles as well, but they're already clickable links so maybe not worth the effort)_

If you agree with the feature in principle, I'd be up for opening a PR...

**Comment by tvler** [comment]
Thanks for reaching out I love the show! GitHub links already work because the add the right rel=me tag to them :)

I think the twitter feature kinda starts degrading what’s special about StreetPass, that it uses the simple rel=me web standard and creates a discovery tool around that. There’s already tons of twitter -> mastodon tools out there so I feel like people can still get this value elsewhere!

I have a lot on the roadmap right now, including safari, better federated interop (showing profiles from other federated apps), and adding more profile metadata (avatars, display names etc). If you like the project and are willing to help out on something else, it would be amazing if you take a look at this PR https://github.com/tvler/streetpass/pull/11 . We’re trying to figure out the exact way the official mastodon rails app reconciles links to federated profiles and implement it in typescript for this project.

**Comment by jerodsanto** [comment]
Ok. Keeping it pure, I get it ✊ 

I'm happy to help test out the Safari stuff, if you'd find that useful. As for the other work... you lost me at TypeScript 😜

**Comment by tvler** [comment]
I can send a test app asap! The main problem is that safari is dropping all extension even listeners after you first quit the app. But works perfectly before. Think the problem is because the code I’m transpiling is too modern and uses es modules 🥴
