### ISSUE TITLE
[Feature Request] Option to open in a separate tab instead of popup

### ISSUE THREAD

**Issue by cubical8569** [tvler/streetpass#16]
As for me personally it would be more convenient if I saw info about mastodon accounts on a separate tab. That way there's no distracting page in background and it looks more focused. Also it's annoying that popup closes after clicking a link and to use it another time one has to click 1 or 2 times to open extension once again (2 for me, as the streetpass isn't on main extension panel). 

Please consider adding such functionality. Thank you for your project!

**Comment by tvler** [comment]
this is a great idea! closing in favor of this tracking ticket which was already made https://github.com/tvler/streetpass/issues/10

**Comment by tvler** [comment]
This has been fixed in the next update 2023.8! Currently in review on the chrome webstore & already available on firefox https://github.com/tvler/streetpass/blob/main/extension/src/popup.tsx#L24

Now you can hold the command button while clicking a link on the popup, and the url will open in a background tab leaving the popup open
