### ISSUE TITLE
[Feature Request] Take moved accounts into account

### ISSUE THREAD

**Issue by shaedrich** [tvler/streetpass#55]
When someone moved instances, it would be nice to see that reflected in the UI. Furthermore, it would be even nicer, if the accounts would be grouped together so that you don't have to search for the current account. Is that possible?

**Comment by tvler** [comment]
Hi! I think this is really interesting, but probably not something I'll be working on. 

Something like this would require tapping into the activitypub api to get working. From my research, any instance that turns on "secure mode" (https://docs.joinmastodon.org/admin/config/#authorized_fetch) will not your installation of StreetPass to hit their activitypub api, since "secure mode" requires a signature from a centralized entity to use their API. Turns out actually a ton of instances have this on

for privacy and simplicity, StreetPass runs 100% locally in your browser, so it would be impossible for a setup like this to work since there's no centralized server associated with StreetPass at all that could sign for these requests!
