### ISSUE TITLE
[Bug] Extension does not appear to work with I2P's Mastodon account.

### ISSUE THREAD

**Issue by Binzy-Boi** [tvler/streetpass#56]
Visiting [I2P's website](https://geti2p.net/en/) with the StreetPass Extension enabled in Firefox does not appear to detect their Mastodon account. Unknown as to why this is.

**Comment by tvler** [comment]
Hi! this is because that website that website doesn't have the correct HTML to link that website to their mastodon profile 
<img width="649" alt="image" src="https://github.com/tvler/streetpass/assets/4934193/c1cf8e28-77be-4565-a3e0-92842d3d638e">

See https://docs.joinmastodon.org/user/profile/#verification
